### ISSUE TITLE
Doesn't track personal reputations in Pandaria

### ISSUE THREAD

**Issue by joegnis** [LorenzoRogai/RepHub#3]
It doesn't track properly: Nat Pagle under the Anglers and those under the Tillers. 
My toon is exalted with the Anglers but not with Nat Pagle, plus exalted with the Tillers and all people in the Tillers. 
The addon shows "42000 (Exalted)" for all those sub-factions, which is wrong. It should show in my case: Buddy (3/6) for Nat Pagle, and Best Friends (6/6) for the Tiller ppl.

**Comment by LorenzoRogai** [comment]
I can confirm the bug, i'm going to check this

**Comment by LorenzoRogai** [comment]
I implemented a first version here https://github.com/LorenzoRogai/RepHub/commit/1529f3fc4cd916539517af5d481bf7d7d121abac and the issue should be solved now. The total standing value is now showing correctly

I'll have to check on how align the labels (Buddy instead of Neutral etc) and show the ranks (3/6, 6/6 etc) but i will probably handle this in a future update
